### ISSUE TITLE
cannot find `compilerSpecific.h`

### ISSUE THREAD

**Issue by zhichu** [paulscherrerinstitute/QtAD#2]
```
../../base/include/compilerDependencies.h:20:10: fatal error: compilerSpecific.h: No such file or directory
   20 | #include "compilerSpecific.h"
      |          ^~~~~~~~~~~~~~~~~~~~
```

Actually `compilerSpecific.h` is located `$$(EPICS_BASE)/include/compiler/gcc`. I did not have this problem before, so the `EPICS` team might have moved the header file.

After adding the location to the `QtAD.pro`, everything works as expected.

**Comment by xiaoqiangwang** [comment]
Thanks for spotting the problem. EPICS base 3.15+ splits out compiler headers to *include/compiler/<compiler>*. Commit 12a0b24 has the fix.
